clear,clc

% Loading the data file.
load('Aircraft_531.mat') % You have to modify this line for other aircraft and mode.
 
% Transform the moment of inertia from body coordinates to stability
% coordinates
[I_xx_s, I_yy_s, I_zz_s, I_xz_s]...
    = MOI_trasnform(...
    I_xx_B, I_yy_B, I_zz_B, I_xz_B,...
    alpha);

% Calculate the longitudinal dimensional derivative
[X_u, X_T_u, X_alpha, X_delta_e, Z_u, Z_alpha, Z_alpha_dot,...
    Z_q, Z_delta_e, M_u, M_T_u, M_alpha, M_T_alpha, M_alpha_dot,...
    M_q, M_delta_e] ...
    = Longitudinal_derivatives(qbar, S, m, u1, I_yy_s, cbar,...
    C_D_u, C_D_1, C_T_x_u, C_T_x_1, C_D_alpha, C_L_1,...
    C_D_delta_e, C_L_u, C_L_alpha, C_L_alpha_dot,...
    C_L_q, C_L_delta_e, C_m_u, C_m_1, C_m_T_u, C_m_T_1,...
    C_m_alpha, C_m_T_alpha, C_m_alpha_dot, C_m_q, C_m_delta_e);

% Calculate the lateral-directional dimensional derivative
[Y_beta, Y_p, Y_r, Y_delta_a, Y_delta_r,...
    L_beta, L_p, L_r, L_delta_a, L_delta_r,...
    N_beta, N_T_beta, N_p, N_r, N_delta_a, N_delta_r]...
    = Lateral_derivatives(qbar, S, u1, m, b, I_xx_s, I_zz_s,...
    C_y_beta, C_y_p, C_y_r, C_y_delta_a, C_y_delta_r,...
    C_l_beta, C_l_p, C_l_r, C_l_delta_a, C_l_delta_r,...
    C_n_beta, C_n_p, C_n_r, C_n_delta_a, C_n_delta_r, C_n_T_beta);

% Calculate the state space matrices
[A_long, B_long, A_lat, B_lat]...
    = State_space_model(...
    alpha, u1, I_xz_s, I_xx_s, I_yy_s, I_zz_s,...
    X_u, X_T_u, X_alpha, X_delta_e, Z_u, Z_alpha, Z_alpha_dot,...
    Z_q, Z_delta_e, M_u, M_T_u, M_alpha, M_T_alpha, M_alpha_dot,...
    M_q, M_delta_e,...
    Y_beta, Y_p, Y_r, Y_delta_a, Y_delta_r,...
    L_beta, L_p, L_r, L_delta_a, L_delta_r,...
    N_beta, N_T_beta, N_p, N_r, N_delta_a, N_delta_r);

A_lat
%A_long
B_lat
B_long